// android/ and ios/ are not in git: they are generated by `expo prebuild`
// (see README / INFO.md). The few things that used to be edited by hand in
// those folders live here instead, so every prebuild puts them back.
const fs = require("fs");
const path = require("path");
const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");

const POD_TARGET_MARKER = "# [withNativeTweaks] clamp pod deployment targets";

// react_native_post_install only raises a pod's deployment target up to the
// app's minimum (15.1) - it never lowers one. A pod whose podspec asks for
// more (e.g. 16.0) keeps compiling against it, which can weak-link APIs
// wrongly and crash through dyld at launch on iOS 15. Forcing every pod down
// to the app's own target turns that into a build-time availability error.
const POD_TARGET_BLOCK = `
    ${POD_TARGET_MARKER}
    app_deployment_target = podfile_properties['ios.deploymentTarget'] || '15.1'
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
        build_config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = app_deployment_target
      end
    end
`;

const withPodDeploymentTarget = (config) =>
  withDangerousMod(config, [
    "ios",
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, "Podfile");
      if (!fs.existsSync(podfile)) return cfg;

      const contents = fs.readFileSync(podfile, "utf8");
      if (contents.includes(POD_TARGET_MARKER)) return cfg;

      // Right after the react_native_post_install(...) call, inside post_install.
      const next = contents.replace(
        /(react_native_post_install\([\s\S]*?\n\s*\)\n)/,
        `$1${POD_TARGET_BLOCK}`
      );
      if (next === contents) {
        console.warn("[withNativeTweaks] react_native_post_install not found in Podfile; deployment targets not clamped");
        return cfg;
      }
      fs.writeFileSync(podfile, next);
      return cfg;
    },
  ]);

// Large screens (tablets, foldables, split screen): Google Play's large
// screen quality rules want the activity resizeable even though the app
// itself stays portrait.
const withResizeableActivity = (config) =>
  withAndroidManifest(config, (cfg) => {
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(cfg.modResults);
    activity.$["android:resizeableActivity"] = "true";
    return cfg;
  });

// CI signs the APK with this keystore. It is kept outside android/ so every
// build - whichever machine prebuilt the project - has the same signature;
// with a different one, Android refuses to install the APK over an existing
// install.
const withStableDebugKeystore = (config) =>
  withDangerousMod(config, [
    "android",
    (cfg) => {
      const source = path.join(cfg.modRequest.projectRoot, "keystores", "debug.keystore");
      const target = path.join(cfg.modRequest.platformProjectRoot, "app", "debug.keystore");
      if (fs.existsSync(source) && fs.existsSync(path.dirname(target))) {
        fs.copyFileSync(source, target);
      }
      return cfg;
    },
  ]);

module.exports = (config) =>
  withStableDebugKeystore(withResizeableActivity(withPodDeploymentTarget(config)));
